### ISSUE TITLE
Titans sometimes drop on roofs and just die to out of bounds timer

### ISSUE THREAD

**Issue by Kaze-Kami** [R2Northstar/NorthstarMods#301] opened 2022-04-13 09:23 UTC
Had this happen a few times to me now, latest was on 1.6.2, didn't have time to play on 1.6.3 yet.

Can't consistently reproduce the issue but it mostly happens on Complex where there are many roofs to choose from :^)
Happened here most of the time (When facing the wall with the displays while calling the titan): ![image](https://user-images.githubusercontent.com/18683538/163144338-fcbc9255-5eba-411e-9e0f-c063c3584529.png)

Not entirely sure but I think it only happens on Attrition.

**Comment by GeckoEidechse** [comment] 2022-04-13 10:04
If it's only Attrition, that's still a WIP and hasn't officially been released. There are some known issues with navmashes that still need fixing.

Pulling in @F1F7Y to take a look just in case :3

**Comment by F1F7Y** [comment] 2022-04-13 10:05
hi :)

**Comment by F1F7Y** [comment] 2022-04-13 10:14
This only happens on attrition servers because only those have navmeshes. I've already made better complex navs, but I'll test them more today.

Sadly without knowing if the server updated to the better navs we won't know which version has the issue.

Guess more playtesting for me. :)

**Comment by Kaze-Kami** [comment] 2022-04-13 10:19
Yea, figured as much still thought I might let you know. Also if you need help testing let me know ;)

**Comment by rwynx** [comment] 2022-05-10 15:43
My current Northstar version is 1.7.0. Hi, I found this thread while searching to see if anyone else has experienced the same thing. In the Crash Site map, my titan spawned 2 times in a clipped area. I had experienced a similar glitch on the Colony map, my Monarch landed in an area that i cant reach (out of bounds counter) and the titan disappears as soon as the dome shield disappears. It's Attrition, i know it's not perfect yet but nevertheless i wanted to share my experience in here too. Check the video: (it seems i cant post anything above 10MB here so i uploaded the video to @hummusbird 's image host) https://rwyn.catgirls.wtf/prLR1MQ3.mp4

**Comment by GeckoEidechse** [comment] 2024-09-01 23:43
This should be resolved with never navmeshes released in versions since. As such I'm closing as resolved under the assumption that the lack of further reports implies that this issue is no longer occurring.

If the issue is still present for you in latest releases, please re-open this GitHub issue or create a new one.

**Closed by GeckoEidechse** 2024-09-01 23:43 UTC
Labels: bug, navmesh
