### ISSUE TITLE
Smart pistol scan lines dont show up

### ISSUE THREAD

**Issue by NachosChipeados** [R2Northstar/NorthstarMods#689] opened 2023-08-22 22:08 UTC
In vanilla, when locking onto enemies with the smart pistol, you will see some lines come out of the weapon and go to the enemy. these lines dont show up when playing in northstar.

### Steps to reproduce
  1. get smart pistol
  2. lock onto an enemy
  3. no lines

### Specifications
  - Northstar version: 1.18.1, but this has been an issue for quite a while now
  - Platform: Steam

Vanilla:

![1237970_20230822161410_1](https://github.com/R2Northstar/NorthstarMods/assets/103285866/e46b87e6-1bf0-443f-b544-298388852dec)

Northstar:
![Screenshot 2023-08-22 165019](https://github.com/R2Northstar/NorthstarMods/assets/103285866/179c624e-a9dd-41d8-98e0-1903e5acaa55)

**Comment by ASpoonPlaysGames** [comment] 2023-09-03 17:38
Closing this in favour of #698 which got transferred to this repo

**Comment by ASpoonPlaysGames** [comment] 2023-09-03 18:00
uhh, no? this is a duplicate of https://github.com/R2Northstar/NorthstarMods/issues/698 (or vice versa I guess)
![image](https://github.com/R2Northstar/NorthstarMods/assets/66967891/ecd40480-934b-41ce-8721-c85b6bd12115)

**Comment by GeckoEidechse** [comment] 2023-09-03 18:37
those two numbers couldn't be more confusing lmao. I'm gonna promote this issue here as the main one as it's older and close #698 as duplicate then

**Comment by ASpoonPlaysGames** [comment] 2023-09-03 18:48
I have traced this issue back to https://github.com/R2Northstar/NorthstarLauncher/pull/106 (which was merged in April 2022)

Turns out Respawn use a debug overlay for this, which this PR locks behind a ConVar (`enable_debug_overlays`) and also hooks the overlay draw function.

**Comment by uniboi** [comment] 2023-09-03 18:50
lmao

**Comment by BobTheBob9** [comment] 2023-09-03 18:51
what the fuck oh my god

**Comment by H0L0theBard** [comment] 2023-09-03 18:54
so we haven't had a vanilla smart pistol experience for over a year now lmao

**Closed** 2023-10-30 19:29 UTC
Labels: bug, vanilla parity
