### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by MrCrowX** [R2Northstar/NorthstarMods#211] opened 2022-02-14 17:20 UTC
server crashes after 2-4 matches. the error occurs after the end of the round. uninstalling mods didn't help.
steam | win 11
startup args:
+setplaylist private_match 
+mp_gamemode ps
+setplaylistvaroverrides "custom_air_accel_pilot 9000 run_epilogue 0"

[nslog2022-02-14 18-20-29.txt](https://github.com/R2Northstar/NorthstarMods/files/8062666/nslog2022-02-14.18-20-29.txt)
[nslog2022-02-14 18-36-37.txt](https://github.com/R2Northstar/NorthstarMods/files/8062668/nslog2022-02-14.18-36-37.txt)
[nslog2022-02-14 19-07-39.txt](https://github.com/R2Northstar/NorthstarMods/files/8062669/nslog2022-02-14.19-07-39.txt)
[nslog2022-02-14 17-44-10.txt](https://github.com/R2Northstar/NorthstarMods/files/8062670/nslog2022-02-14.17-44-10.txt)
[dumps.zip](https://github.com/R2Northstar/NorthstarMods/files/8062680/dumps.zip)
.

**Comment by GeckoEidechse** [comment] 2022-02-14 20:42
Just to rule out any other sources of problems, are you running any mods on your server?

**Comment by JMM889901** [comment] 2022-02-14 21:55
Do you know any way to cause it consistently? and does it only occur on pilots V pilots?

**Comment by MrCrowX** [comment] 2022-02-14 21:57
I don't know how to call. I only play pvp. I installed the version of northstar 1.4.0 and played quietly for about 2 hours without a crash. played with the mods listed above.

**Comment by JMM889901** [comment] 2022-02-14 22:00
does it occur at any specific time? also are you on northstar 1.5 or 1.4 then? a lot of issues are fixed on 1.5

**Comment by MrCrowX** [comment] 2022-02-14 22:04
this happens when we have finished the round and the map should change. my northstar version is 1.5.0

**Comment by MrCrowX** [comment] 2022-02-14 22:06
for the test, I played for about 2 hours on the server version 1.4.0. game version 1.5.0. the error did not come out, but the server was not full. the error began to appear only when the server was updated to 1.5.0

**Comment by JMM889901** [comment] 2022-02-14 22:19
i cant seem to get it to trigger consistently myself, it might only occur if there are enough players, i have an idea for a "fix" if you would be willing to test it

**Comment by MrCrowX** [comment] 2022-02-14 22:20
of course i want to check it out

**Comment by JMM889901** [comment] 2022-02-14 22:22
if you know how could you try change line 284-296 in _base_gametype_mp.gnut from

```cpp
	table<int, bool> alreadyAssisted
	foreach( DamageHistoryStruct attackerInfo in player.e.recentDamageHistory )
	{
		bool exists = attackerInfo.attacker.GetEncodedEHandle() in alreadyAssisted ? true : false
		if( attackerInfo.attacker != attacker && !exists )
		{
			alreadyAssisted[attackerInfo.attacker.GetEncodedEHandle()] <- true
			Remote_CallFunction_NonReplay( attackerInfo.attacker, "ServerCallback_SetAssistInformation", attackerInfo.damageSourceId, attacker.GetEncodedEHandle(), player.GetEncodedEHandle(), attackerInfo.time ) 
			AddPlayerScore(attackerInfo.attacker, "PilotAssist" )
		}

	}
```

with
```cpp
	table<int, bool> alreadyAssisted
	foreach( DamageHistoryStruct attackerInfo in player.e.recentDamageHistory )
	{
		if(attackerInfo.attacker != svGlobal.worldspawn){ 
		bool exists = attackerInfo.attacker.GetEncodedEHandle() in alreadyAssisted ? true : false
		if( attackerInfo.attacker != attacker && !exists )
		{
			alreadyAssisted[attackerInfo.attacker.GetEncodedEHandle()] <- true
			Remote_CallFunction_NonReplay( attackerInfo.attacker, "ServerCallback_SetAssistInformation", attackerInfo.damageSourceId, attacker.GetEncodedEHandle(), player.GetEncodedEHandle(), attackerInfo.time ) 
			AddPlayerScore(attackerInfo.attacker, "PilotAssist" )
		}
		}

	}
```

make a backup first though, or if you dont know how just dm me on discord and ill send you a mod file to do it

**Comment by JMM889901** [comment] 2022-02-14 22:23
its kind of a dodgy fix since it doesn't really stop the cause of the issue, but might stop the crashing

**Comment by MrCrowX** [comment] 2022-02-14 22:27
well. I'll try it and report back here or on Discord. now it's too late and I won't be able to get a server with players.

**Comment by MrCrowX** [comment] 2022-02-15 15:34
unfortunately it didn't help. server crash again.
[nslog2022-02-15 17-32-03.txt](https://github.com/R2Northstar/NorthstarMods/files/8072435/nslog2022-02-15.17-32-03.txt)
[nsdump2022-02-15 18-32-03.zip](https://github.com/R2Northstar/NorthstarMods/files/8072436/nsdump2022-02-15.18-32-03.zip)

**Comment by GeckoEidechse** [comment] 2022-02-15 21:23
@MrCrowX have you tried #215 yet? That seems to have worked for me ^^

**Closed** 2022-02-15 22:24 UTC
Labels: bug
