### ISSUE TITLE
[Fastball] You can hack panels that already belong to your team.

### ISSUE THREAD

**Issue by Erlite** [R2Northstar/NorthstarMods#169] opened 2022-01-28 19:22 UTC
As the title says, you can keep hacking panels that are already yours, allowing you to infinitely respawn teammates and get a stupid amount of points for no reason.

**Comment by laundmo** [comment] 2022-01-28 19:41
seconded,

this happened on my fastball server using the newest NorthstarMods

**Comment by GeckoEidechse** [comment] 2022-01-28 20:38
This likely a regression caused by 3e98aad76ce9f69eba30770e71518a715991e820

**Comment by GeckoEidechse** [comment] 2022-01-28 21:12
I spoke to soon, just tested reverting 050e707f4762b976791c0934b88779e038f70ade and the regression is gone.
( @BobTheBob9 )

**Comment by GeckoEidechse** [comment] 2022-01-28 21:40
Should be fixed with #171

**Comment by Erlite** [comment] 2022-01-28 22:10
Can't be reverted, needs to be fixed without regressing into the even worse
crash. I can try to take a look and fix it, but I haven't had the chance to
check how things work with Northstar yet ^^'

**Comment by GeckoEidechse** [comment] 2022-01-29 10:52
#171 has been merged so this issue should be fixed for now.

**Closed by GeckoEidechse** 2022-01-29 10:52 UTC
Labels: bug, gamemode
