### ISSUE TITLE
FD Error

### ISSUE THREAD

**Issue by liveskai** [R2Northstar/NorthstarMods#763] opened 2023-11-22 08:54 UTC
```
[16:22:36] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Entity class "CNPC_Titan" doesn't match required class for this index or function call
[16:22:36] [SCRIPT SV] [info]  -> return player.GetPlayerNetBool( "playerAllowedToSyncedMelee" )
[16:22:36] [SCRIPT SV] [info] 
CALLSTACK
*FUNCTION [SyncedMelee_IsAllowed()] melee/sh_melee.gnut line [1174]
*FUNCTION [ShouldPlayerExecuteTarget()] melee/sh_melee.gnut line [1073]
*FUNCTION [CodeCallback_IsValidMeleeExecutionTarget()] melee/sh_melee.gnut line [198]
*FUNCTION [EliteTitanExecutionCheck()] ai/_ai_elite_titans.nut line [55]
*FUNCTION [DamageScaleByDifficulty()] gamemodes/_gamemode_fd.nut line [1972]
*FUNCTION [RunClassDamageCallbacks()] _codecallbacks_common.gnut line [284]
*FUNCTION [CodeCallback_DamagePlayerOrNPC()] mp/_codecallbacks.gnut line [224]
```

**Comment by ASpoonPlaysGames** [comment] 2023-11-22 09:32
Callstack talks about elite titans, so looks like something for @Zanieon

**Comment by Zanieon** [comment] 2023-11-22 11:10
> Callstack talks about elite titans, so looks like something for @Zanieon

Yeah i have split their code away from `_gamemode_fd_events.nut` into their own script, however this callstack points to their execution code which lies in an adapted `sh_melee.gnut` to allow AI to use the same executions as players, i fixed this issue long ago after giving this ability to execute players.

This indicates this file is not updated properly to the one in my branch and is rather using the one bundled with main Northstar releases, line 1174 only points to the callstack line in there, not in the version file of my branch.

User tried to nitpick files to update maybe?

**Comment by liveskai** [comment] 2023-11-23 14:11
https://github.com/Zanieon

**Comment by liveskai** [comment] 2023-11-23 14:11
@Zanieon 
[22:00:28] [SCRIPT SV] [info] [PV] Triggered OnPlayerSpawned
[22:00:29] [NATIVE SV] [info] SERVER: Lunge_SetTargetEntity(): Setting lunge target to (null)
[22:00:29] [NATIVE SV] [info] SERVER: Lunge_SetTargetEntity(): Setting lunge target to (null)
[22:00:30] [NATIVE SV] [info] SERVER: Lunge_SetTargetEntity(): Setting lunge target to (null)
[22:00:32] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Entity class "CNPC_Titan" doesn't match required class for this index or function call
[22:00:32] [SCRIPT SV] [info]  -> return player.HasPassive( passive )
[22:00:32] [SCRIPT SV] [info] 
CALLSTACK
*FUNCTION [PlayerHasPassive()] sh_passives.gnut line [384]
*FUNCTION [HandleBlockingAndCalcDamageScaleForHit()] weapons/mp_titanability_basic_block.nut line [210]
*FUNCTION [BasicBlock_OnDamage()] weapons/mp_titanability_basic_block.nut line [313]
*FUNCTION [RunClassDamageFinalCallbacks()] _codecallbacks_common.gnut line [307]
*FUNCTION [CodeCallback_DamagePlayerOrNPC()] mp/_codecallbacks.gnut line [285]
*FUNCTION [FireWeaponBullet()] NATIVE line [-1]
*FUNCTION [FireWeaponPlayerAndNPC()] weapons/mp_titanweapon_predator_cannon.nut line [266]
*FUNCTION [OnWeaponPrimaryAttack_titanweapon_predator_cannon()] weapons/mp_titanweapon_predator_cannon.nut line [199]
*FUNCTION [OnWeaponNpcPrimaryAttack_titanweapon_predator_cannon()] weapons/mp_titanweapon_predator_cannon.nut line [253]

**Comment by liveskai** [comment] 2023-11-23 14:15
Because I'm NSCN and didn't replace all the files

**Comment by liveskai** [comment] 2023-11-23 14:15
Replaced the melee now and it's still reporting an error

**Comment by Zanieon** [comment] 2023-11-24 13:27
Honestly at this point i legit don't know what's going on in with NSCN, all of those errors does not show up at the original NS when fully utilizing my branch. Errors are now pointing to vanilla functions outside of modified files by Northstar (i.e `sh_passives.gnut`)

**Comment by liveskai** [comment] 2023-11-29 13:02
[20:56:19] [NORTHSTAR] [info] [KCP] Disconnecting local <--> [::ffff:111.166.104.144]:37005%13
[20:56:22] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Attempted to call IsPlayer on invalid entity
[20:56:22] [SCRIPT SV] [info]  -> if ( animatingEnt.IsPlayer() )
[20:56:22] [SCRIPT SV] [info] 
CALLSTACK
*FUNCTION [WaittillAnimDone_Thread()] _utility_shared.nut line [3430]

[20:56:22] [SCRIPT SV] [info] LOCALS
[animatingEnt] ENTITY (NULL)
[this] TABLE

DIAGPRINTS

@Zanieon

**Comment by liveskai** [comment] 2023-12-01 16:20
```
[11:23:22] [NATIVE SV] [warning] EmitSoundOnEntityExceptToPlayer: Unknown sound - Weapon_Titan_Sniper_LevelTick_10; Entity is 'weaponx mp_titanweapon_sniper [285]'
[11:23:22] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Attempted to call IsPlayer on invalid entity
[11:23:22] [SCRIPT SV] [info]  -> if ( animatingEnt.IsPlayer() )
[11:23:22] [SCRIPT SV] [info] 
CALLSTACK
*FUNCTION [WaittillAnimDone_Thread()] _utility_shared.nut line [3430]

[11:23:22] [SCRIPT SV] [info] LOCALS
[animatingEnt] ENTITY (NULL)
[this] TABLE

DIAGPRINTS
```

**Comment by Zanieon** [comment] 2023-12-04 19:40
> ```
> [22:16:56] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Attempted to call GetTitanSoul on invalid entity
> [22:16:56] [SCRIPT SV] [info]  -> entity soul = ent.GetTitanSoul()
> [22:16:56] [SCRIPT SV] [info] 
> CALLSTACK
> *FUNCTION [EliteExecutionDelayed()] ai/_ai_elite_titans.nut line [73]
> 
> [22:16:56] [SCRIPT SV] [info] LOCALS
> [ent] ENTITY (NULL)
> [attacker] ENTITY (npc_titan npc_titan_atlas_vanguard [933] (NPC "npc_titan_atlas_vanguard_boss_fd_elite" at <-4580.45 390.021 138.029>))
> [this] TABLE
> 
> DIAGPRINTS
> ```

Okay this one is reasonable, will fix it with the next update, has to do with people disconnecting right in the frame of recieving a melee attack from an Elite Titan.

**Comment by liveskai** [comment] 2023-12-05 04:59
> Honestly at this point i legit don't know what's going on with NSCN, all of those errors does not show up at the original NS when fully utilizing my branch. Errors are now pointing to vanilla functions outside of modified files by Northstar (i.e `sh_passives.gnut`)

This issue has been fixed

**Comment by liveskai** [comment] 2023-12-05 04:59
> SCRIPT

This issue has been fixed

**Comment by liveskai** [comment] 2023-12-05 05:00
> @Zanieon
> 
> ```
> [22:00:28] [SCRIPT SV] [info] [PV] Triggered OnPlayerSpawned
> [22:00:29] [NATIVE SV] [info] SERVER: Lunge_SetTargetEntity(): Setting lunge target to (null)
> [22:00:29] [NATIVE SV] [info] SERVER: Lunge_SetTargetEntity(): Setting lunge target to (null)
> [22:00:30] [NATIVE SV] [info] SERVER: Lunge_SetTargetEntity(): Setting lunge target to (null)
> [22:00:32] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Entity class "CNPC_Titan" doesn't match required class for this index or function call
> [22:00:32] [SCRIPT SV] [info]  -> return player.HasPassive( passive )
> [22:00:32] [SCRIPT SV] [info] 
> CALLSTACK
> *FUNCTION [PlayerHasPassive()] sh_passives.gnut line [384]
> *FUNCTION [HandleBlockingAndCalcDamageScaleForHit()] weapons/mp_titanability_basic_block.nut line [210]
> *FUNCTION [BasicBlock_OnDamage()] weapons/mp_titanability_basic_block.nut line [313]
> *FUNCTION [RunClassDamageFinalCallbacks()] _codecallbacks_common.gnut line [307]
> *FUNCTION [CodeCallback_DamagePlayerOrNPC()] mp/_codecallbacks.gnut line [285]
> *FUNCTION [FireWeaponBullet()] NATIVE line [-1]
> *FUNCTION [FireWeaponPlayerAndNPC()] weapons/mp_titanweapon_predator_cannon.nut line [266]
> *FUNCTION [OnWeaponPrimaryAttack_titanweapon_predator_cannon()] weapons/mp_titanweapon_predator_cannon.nut line [199]
> *FUNCTION [OnWeaponNpcPrimaryAttack_titanweapon_predator_cannon()] weapons/mp_titanweapon_predator_cannon.nut line [253]
> ```
This issue has been fixed

**Comment by liveskai** [comment] 2023-12-05 05:12
```
[13:11:13] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Damage 576000.000000 over max damage value of 524287
[13:11:13] [SCRIPT SV] [info]  -> DamageInfo_SetDamage( damageInfo, floor( DamageInfo_GetDamage( damageInfo ) + 0.5 ) )
[13:11:13] [SCRIPT SV] [info] 
CALLSTACK
*FUNCTION [CodeCallback_DamagePlayerOrNPC()] mp/_codecallbacks.gnut line [198]

[13:11:13] [SCRIPT SV] [info] LOCALS
[attackerIsNPC] false
[attackerIsTitan] true
[attackerIsPlayer] true
[inflictor] ENTITY (crossbow_bolt [611] at <-1223.15 2573.34 214.951>)
[attacker] ENTITY (player Activision-NMSL [1] (player "Activision-NMSL" at <-3708.99 4223.57 -212.624>))
[entIsNPC] true
[entIsTitan] true
[entIsPlayer] false
[damageInfo] INSTANCE
[ent] ENTITY (npc_titan npc_titan_atlas_stickybomb [664] (NPC "npc_titan_atlas_stickybomb_boss_fd" at <-1323.49 2621.52 10.7017>))
[this] TABLE

DIAGPRINTS
```

**Comment by liveskai** [comment] 2023-12-07 05:40
Client reports error after mp_lf_township ends
![Titanfall 2 2023 12 07 - 13 36 30 05 DVR mp4_20231207_133837 888](https://github.com/R2Northstar/NorthstarMods/assets/54350655/fe6d5ae7-0811-46a7-b8fe-703510406cac)

**Comment by liveskai** [comment] 2023-12-07 05:40
@Zanieon

**Comment by Zanieon** [comment] 2023-12-07 08:32
Again issue related to people disconnecting when stuff is about to happen.

**Comment by liveskai** [comment] 2024-01-07 14:30
[22:29:47] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Attempted to call Minimap_SetAlignUpright on invalid entity
[22:29:47] [SCRIPT SV] [info]  -> human.Minimap_SetAlignUpright( true )
[22:29:47] [SCRIPT SV] [info] 
CALLSTACK
*FUNCTION [AddMinimapForHumans()] gamemodes/_gamemode_fd_events.nut line [2426]
*FUNCTION [spawnDroppodGrunts()] gamemodes/_gamemode_fd_events.nut line [1341]

[22:29:47] [SCRIPT SV] [info] LOCALS
[human] ENTITY (NULL)
[this] TABLE
[@ITERATOR@] 1
[npc] ENTITY (NULL)
[@INDEX@] 0
[guys] ARRAY
[at_weapon] "mp_weapon_defender"
[squadName] "squad_imc_us1137"
[pod] ENTITY (prop_dynamic [740] at <3894 10 79.4805>)
[soundEvent] unknown struct
[flowControlEvent] unknown struct
[spawnEvent] unknown struct
[smokeEvent] unknown struct
[this] TABLE

DIAGPRINTS

**Comment by liveskai** [comment] 2024-01-07 14:30
@Zanieon

**Comment by Zanieon** [comment] 2024-01-07 18:34
That one was fixed in https://github.com/Zanieon/NorthstarMods/commit/2fc8c6ce95e0c1b0bfdc32bb8f2900b3578c41ee

**Comment by liveskai** [comment] 2024-01-09 13:54
> That one was fixed in [Zanieon@2fc8c6c](https://github.com/Zanieon/NorthstarMods/commit/2fc8c6ce95e0c1b0bfdc32bb8f2900b3578c41ee)

```
[21:18:13] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Index "0" is beyond array size of 0
[21:18:13] [SCRIPT SV] [info]  -> entity weapon = primaryWeapons[0]
[21:18:13] [SCRIPT SV] [info] 
CALLSTACK
*FUNCTION [spawnSuperSpectre()] gamemodes/_gamemode_fd_events.nut line [1237]

[21:18:13] [SCRIPT SV] [info] LOCALS
[primaryWeapons] ARRAY
[npc] ENTITY (npc_super_spectre reaper [776] (NPC "npc_super_spectre_fd" at <4014 -111 -417>))
[spawnorigin] <4014, -111, -417>
[soundEvent] unknown struct
[flowControlEvent] unknown struct
[spawnEvent] unknown struct
[smokeEvent] unknown struct
[this] TABLE

DIAGPRINTS
```

**Comment by liveskai** [comment] 2024-01-09 13:55
```
[12:33:19] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] Attempted to call SetEfficientMode on invalid entity
[12:33:19] [SCRIPT SV] [info]  -> npc.SetEfficientMode( false )
[12:33:19] [SCRIPT SV] [info] 
CALLSTACK
*FUNCTION [spawnDroppodGrunts()] gamemodes/_gamemode_fd_events.nut line [1358]

[12:33:19] [SCRIPT SV] [info] LOCALS
[@ITERATOR@] 1
[npc] ENTITY (NULL)
[@INDEX@] 0
[guys] ARRAY
[at_weapon] "mp_weapon_defender"
[squadName] "squad_imc_us1599"
[pod] ENTITY (prop_dynamic [299] at <1709 -1091 75.4805>)
[soundEvent] unknown struct
[flowControlEvent] unknown struct
[spawnEvent] unknown struct
[smokeEvent] unknown struct
[this] TABLE

DIAGPRINTS
```

**Comment by liveskai** [comment] 2024-01-18 02:14
![I$Z4BGHZ8 L0(4C(X%9@7}N](https://github.com/R2Northstar/NorthstarMods/assets/54350655/71eab2ae-4ba1-4958-8097-018767da5b3b)
@Zanieon

**Comment by GeckoEidechse** [comment] 2024-01-18 17:10
@liveskai just a heads-up that as you are running NorthstarCN and not upstream Northstar, the issue might be caused by the NorthstarCN fork instead ^^"

Please double check if you can reproduce the issue using upstream Northstar before making an issue here and if not, report the issue to NorthstarCN first.

Thanks for taking this into consideration <3

**Comment by liveskai** [comment] 2024-01-19 04:03
> *FUNCTION [spawnDroppodGrunts()] gamemodes/_gamemode_fd_events.nut line [1358]

*FUNCTION [spawnDroppodGrunts()] gamemodes/_gamemode_fd_events.nut line [1358]
This won't be an NSCN issue, NSCN doesn't have FD mode

**Comment by Zanieon** [comment] 2024-02-09 22:00
Closing this due to lack of activity plus problems not directly related to FD branch but rather incompatibilities between FD branch and NSCN codebase.

**Closed by Zanieon** 2024-02-09 22:00 UTC
