### ISSUE TITLE
Spawning titan without full titan meter

### ISSUE THREAD

**Issue by ASpoonPlaysGames** [R2Northstar/NorthstarMods#339] opened 2022-05-04 05:42 UTC
Spawning titan without full titan meter: https://clips.twitch.tv/TolerantIgnorantBisonRickroll-i-XEjpouG0tBVVX6

_Originally posted by @L1ghtman2k in https://github.com/R2Northstar/NorthstarMods/issues/338#issuecomment-1116861421_

Unsure if this is CTF specific, so making a separate issue for it

**Comment by GeckoEidechse** [comment] 2022-05-04 08:00
I've experienced this in Attrition as well so definitely not CTF specific. So far I don't think anyone has managed to consistently reproduce it though :/

**Comment by gas3d** [comment] 2022-05-14 10:45
I managed to reproduce the glitch in Attrition, using Monarch. Instead of calling in my Titan i would spawn in as the Titan, then once the upgrade core meter was full i would die and could immediately either call in another Titan or spawn in again as the titan.

This can probably be done on other Titans as long as you die with your ability meter full.

**Comment by ASpoonPlaysGames** [comment] 2023-08-25 17:50
this actually may be a duplicate of #256

**Comment by Zanieon** [comment] 2024-11-27 13:16
Duplicate of an apparent fixed issue.

**Closed by Zanieon** 2024-11-27 13:16 UTC
Labels: bug, duplicate
