### ISSUE TITLE
Titans can teleport to bad positions due to navmeshes

### ISSUE THREAD

**Issue by L1ghtman2k** [R2Northstar/NorthstarMods#337] opened 2022-05-03 17:30 UTC
Titans teleport on disembarking, in spots where they typically don't do that

Examples:
 - War Games: https://streamable.com/37bfwl
 - Drydock: https://streamable.com/lmhj68
 - Boomtown https://streamable.com/tsur9w & https://streamable.com/7f9d6q

**We have tested the above on 1.6.4, and these issues DID NOT exist prior to 1.7.0**

**Comment by L1ghtman2k** [comment] 2022-05-03 19:00
https://streamable.com/8zqcrw

**Comment by GeckoEidechse** [comment] 2022-05-03 19:03
Given that the only changes between `v1.6.4` and `v1.7.0` are the following https://github.com/R2Northstar/NorthstarMods/compare/b715a69c711d56490657a3057f3faba8fb26aa48...311affdb844905f5277a9f9a757ac20cdf3995ff and Navmeshes, I feel confident in claiming that issue likely lies with the latter.

@taskinoz any ideas?

**Comment by GeckoEidechse** [comment] 2022-05-03 19:07
@L1ghtman2k maybe try deleting navmeshes and graphs by deleting the following folders on server host:

- `R2Northstar/mods/Northstar.CustomServers/mod/maps/graphs`
- `R2Northstar/mods/Northstar.CustomServers/mod/maps/navmesh`

Then restart game of host and try the same spots again. If you now no longer get teleported, the issue is with navs.

**Comment by F1F7Y** [comment] 2022-05-03 19:11
This looks like the game is trying to correct ai positions by teleporting the titan. The titan only navs were cut down to only include geometry reachable by titans, but it seems like it has some problems and oversights. :)

The solution I see as of now is:
- We PR new, better navs done by hand like the rest. This is expected and is a part of the process of improving ai as time moves on

A more future-proof solution would be:
- We make a python script and reverse collision masks to automate the process :)

**Comment by BobTheBob9** [comment] 2022-05-03 20:28
if navmeshes are the issue, we could probably just change the disembark scripts to be able to disable the navmesh usage there

**Comment by BobTheBob9** [comment] 2022-05-03 20:28
this is assuming that it's specifically a disembark issue and not just an ai one

**Comment by taskinoz** [comment] 2022-05-03 23:34
These are definitely navmesh issues.
I forgot about the hallway in wargames, and removed that bridge from drydock, because I though titans shouldn't drop up there.
And boomtown navs havent been updated to fix titan stuff.

**Comment by L1ghtman2k** [comment] 2022-07-11 15:37
Hey @taskinoz, I was wondering if you could confirm @GeckoEidechse [comment](https://github.com/R2Northstar/NorthstarMods/issues/337#issuecomment-1116462157)

I was wondering if deleting those files would suffice to fix the teleport issues(assuming of course titans lose the capability to move and use navmesh)

**Comment by L1ghtman2k** [comment] 2022-07-11 17:51
Nvm, Seems like it works, I just had it tested, and wargames/drydock don't have the same issues anymore, Thanks @GeckoEidechse

**Comment by taskinoz** [comment] 2022-07-12 04:18
Removing Navs like Gecko said will get rid of the teleporting issues till I can remake them

**Comment by Zanieon** [comment] 2024-08-03 01:26
Closing this as the navmeshes have been rebuilt by me and this issue is pretty much fixed in all maps.

**Closed by Zanieon** 2024-08-03 01:26 UTC
Labels: bug, navmesh
