### ISSUE TITLE
CTF spawns you occasionally near enemy team flag

### ISSUE THREAD

**Issue by fvnkhead** [R2Northstar/NorthstarMods#476] opened 2022-08-07 05:10 UTC
On something like Angel City, you can sometimes spawn at the side of the map that is opposite to your team's side

**Comment by L1ghtman2k** [comment] 2022-08-10 16:28
Duplicate of https://github.com/R2Northstar/NorthstarMods/issues/177 and https://github.com/R2Northstar/NorthstarMods/issues/338

**Closed** 2022-08-10 16:36 UTC
Labels: duplicate
