### ISSUE TITLE
Dying inside of a titan sometimes allows you to drop a titan just after

### ISSUE THREAD

**Issue by Legonzaur** [R2Northstar/NorthstarMods#368] opened 2022-05-22 19:08 UTC
Some videos to illustrate

https://cdn.discordapp.com/attachments/977997240599728268/978002227404881990/First_game.mp4

https://cdn.discordapp.com/attachments/977997240599728268/978002259529072790/Second_game.mp4

It seems to work only when using "respawn as a titan" (or so it seems)

**Comment by ASpoonPlaysGames** [comment] 2023-08-25 17:48
closing as potential duplicate of #339

**Closed by ASpoonPlaysGames** 2023-08-25 17:48 UTC
Labels: duplicate
